name: CLGroups
main: de.craftlancer.groups.CLGroups
version: ${project.version}
description: Some Utility Stuff for Craftlancer
depend: [CLCore]
commands:
  faction:
    usage: /faction
  town:
    usage: /town
  plot:
    usage: /plot
  ch:
    usage: /ch
  msg:
    usage: /msg <player> <message>
  re:
    usage: /re <message>