package de.craftlancer.groups;

import org.bukkit.configuration.file.FileConfiguration;

public class GroupLanguage
{
    public static String GAME_BUILD_FORBIDDEN = "Du kannst hier nicht bauen.";
    public static String COMMAND_GENERAL_UNABLE = "Du kannst diesen Befehl nicht ausführen.";
    public static String COMMAND_GENERAL_NOTINFACTION = "Du musst in einer Fraktion sein, um diesen Befehl auszuführen.";
    public static String COMMAND_GENERAL_NOTINTOWN = "Du musst in einer Stadt sein, um diesen Befehl auszuführen.";
    public static String COMMAND_GENERAL_FACTION_PERMISSION = "Du besitzt nicht die nötigen Fraktionsberechtigungen für diesen Befehl.";
    public static String COMMAND_GENERAL_TOWN_PERMISSION = "Du besitzt nicht die nötigen Stadtberechtigungen.";
    public static String COMMAND_GENERAL_ARGUMENTS = "Dieser Befehl bedarf mehr Argumente.";
    public static String COMMAND_GENERAL_NOTONLINE = "Das Ziel ist nicht online.";
    public static String COMMAND_GENERAL_NOTOWN = "Stadt nicht gefunden.";
    public static String COMMAND_GENERAL_NOFACTION = "Fraktion nicht gefunden.";
    public static String COMMAND_GENERAL_NOPLAYER = "Dieser Spieler existiert nicht.";
    public static String COMMAND_GENERAL_NOTANUMBER = "Ein angegebenes Argument ist keine Zahl.";
    public static String COMMAND_GENERAL_NOTSTRINGFORMAT = "Der Befehl folgt nicht dem String Format!";
    public static String COMMAND_CHAT_JOIN_FACTION = "Du bist jetzt im Fraktions Channel.";
    public static String COMMAND_CHAT_JOIN_GLOBAL = "Du bist jetzt im globalen Channel.";
    public static String COMMAND_CHAT_JOIN_LOCAL = "Du bist jetzt im lokalen Channel.";
    public static String COMMAND_CHAT_JOIN_TOWN = "Du bist jetzt im Stadt Channel.";
    public static String COMMAND_CHAT_NOPARTNER = "Chatpartner nicht gefunden.";
    public static String COMMAND_FACTION_COLOR_NOTACOLOR = "Dies ist keine Farbe.";
    public static String COMMAND_FACTION_COLOR_TAKEN = "Diese Farbe ist bereits vergeben.";
    public static String COMMAND_FACTION_COLOR_SUCCESS = "Fraktionsfarbe erfolgreich gesetzt.";
    public static String COMMAND_FACTION_NOTAREPU = "Nur WAR, HOSTILE, NEUTRAL, FRIEND und ALLIED sind erlaubt.";
    public static String COMMAND_FACTION_DEFAULTREP_SUCCESS = "Standardreputation erfolgeich gesetzt.";
    public static String COMMAND_FACTION_GIFT_NOTYOURTOWN = "Diese Stadt gehört nicht zu deiner Fraktion.";
    public static String COMMAND_FACTION_GIFT_LASTTOWN = "Du kannst die letzte Stadt deiner Fraktion nicht verschenken.";
    public static String COMMAND_FACTION_INFO_HEADER = "Fraktion: ";
    public static String COMMAND_FACTION_LIST_HEADER = "§3 ==== Fraktionen ====";
    public static String COMMAND_FACTION_NEW_FACTION_INFACTION = "Du bist bereits in einer Fraktion.";
    public static String COMMAND_FACTION_NEW_DISTANCE = "Du bist zu nah an einem anderen Spieler/einer anderen Stadt.";
    public static String COMMAND_FACTION_NEW_TOWNEXISTS = "Es existiert bereits eine Stadt mit diesem Namen.";
    public static String COMMAND_FACTION_NEW_FACTIONEXISTS = "Es existiert bereits eine Fraktion mit diesem Namen.";
    public static String COMMAND_FACTION_NEW_SUCCESS = "Fraktionsgründung erfolgreich.";
    public static String COMMAND_FACTION_NEW_BROADCAST = "Die Fraktion %1$s mit der Hauptstadt %2$s wurde gegründet.";
    public static String COMMAND_FACTION_RENAME_BROADCAST = "Die Fraktion %1$s wurde in %2$s umbenannt!";
    public static String COMMAND_FACTION_RENAME_EXISTS = "Es existiert bereits eine Fraktion mit diesem Namen.";
    public static String COMMAND_FACTION_RENAME_SUCCESS = "Fraktion erfolgreich umbenannt.";
    public static String COMMAND_FACTION_SETREP_SUCCESS = "Reputation für %1$s %2$s erfolgreich gesetzt.";
    public static String COMMAND_FACTION_SHOWREP_HEADER = "%1$s's Reputation: ";
    public static String COMMAND_FACTION_SHOWREP_CONTENT = "%1$s zu %2$s: %3$s";
    public static String COMMAND_FACTION_TAG_TAKEN = "Dieser Tag ist bereits vergeben.";
    public static String COMMAND_FACTION_TAG_SUCCESS = "Fraktions Tag erfolgreich gesetzt.";
    public static String COMMAND_GROUP_NOSUCHGROUP = "Die angegebene Gruppe existiert nicht.";
    public static String COMMAND_GROUP_ADD_SUCCESS = "Spieler erfolgreich zur Gruppe hinzugefügt.";
    public static String COMMAND_GROUP_PROTECTED = "Diese Gruppe ist geschützt und kann mit diesen Befehl nicht editiert werden.";
    public static String COMMAND_GROUP_ADDPERM_SUCCESS = "Berechtigungen erfolgreich zur Gruppe hinzugefügt.";
    public static String COMMAND_GROUP_DELETE_SUCCESS = "Gruppe erfolgreich gelöscht.";
    public static String COMMAND_GROUP_INFO_HEADER = "Gruppe: ";
    public static String COMMAND_GROUP_LIST_HEADER = "Gruppen: ";
    public static String COMMAND_GROUP_EXISTS = "Diese Gruppe existiert bereits.";
    public static String COMMAND_GROUP_NEW_SUCCESS = "Gruppe erfolgreich erstellt.";
    public static String COMMAND_GROUP_REMOVE_SUCCESS = "Spieler erfolgreich aus Gruppe entfernt.";
    public static String COMMAND_GROUP_REMOVEPERM_SUCCESS = "Berechtigung erfolgreich von Gruppe entfernt.";
    public static String COMMAND_PLOT_NOTOWNER = "Dieser Plot gehört nicht dir.";
    public static String COMMAND_PLOT_ADD_SUCCESS = "Spieler erfolgreich zu Plot hinzugefügt.";
    public static String COMMAND_PLOT_CLAIM_NOTFORSALE = "Dieser Plot steht nicht zum verkauf.";
    public static String COMMAND_PLOT_CLAIM_TOOCLOSE = "Dieser Plot ist zu nah an einer Stadt/einem anderen Spieler.";
    public static String COMMAND_PLOT_CLAIM_LIMIT = "Du besitzt bereits die maximale Anzahl von Plots.";
    public static String COMMAND_PLOT_CLAIM_SUCCESS = "Plot erfolgreich gekauft.";
    public static String COMMAND_PLOT_GIFT_LIMIT = "Dieser Spieler hat bereits sein Plotlimit erreicht.";
    public static String COMMAND_PLOT_GIFT_SUCCESS = "Plot erfolgreich verschenkt.";
    public static String COMMAND_PLOT_GIFT_GIFTED = "Dir wurde der Plot %1$s von %2$s geschenkt.";
    public static String COMMAND_PLOT_LEAVE_SUCCESS = "Du hast den Plot erfolgreich verlassen.";
    public static String COMMAND_PLOT_LIST_HEADER = "Deine Plots: ";
    public static String COMMAND_PLOT_REMOVE_SUCCESS = "Spieler erfolgreich vom Plot entfernt.";
    public static String COMMAND_PLOT_SALE_SUCCESS = "Plot erfolgreich zum Verkauf gestellt.";
    public static String COMMAND_PLOT_UNSALE_SUCCESS = "Dieser Plot steht nun nichtmehr zum Verkauf.";
    public static String COMMAND_TOWN_FAREWELL_SUCCESS = "Abschiedsnachricht erfolgreich gesetzt.";
    public static String COMMAND_TOWN_INFO_HEADER = "Stadt Info: ";
    public static String COMMAND_TOWN_INVITE_ALREADYINTOWN = "Dieser Spieler ist bereits in einer Stadt.";
    public static String COMMAND_TOWN_INVITE_SUCCESS = "Spieler erfolgreich eingeladen.";
    public static String COMMAND_TOWN_INVITE_QUESTION = "Möchtest du der Stadt %1$s (Fraktion %2$s) betreten? [yes|no]";
    public static String COMMAND_TOWN_KICK_SELF = "Du kannst dich nicht selbst aus deiner Stadt werfen.";
    public static String COMMAND_TOWN_KICK_NOTINTOWN = "Dieser Spieler ist nicht Mitglied deiner Stadt.";
    public static String COMMAND_TOWN_KICK_SUCCESS = "Du hast %1$s erfolgreich aus der Stadt geworfen.";
    public static String COMMAND_TOWN_KICK_KICKED = "Du wurdest aus der Stadt geworfen.";
    public static String COMMAND_TOWN_KICK_BROADCASTKICKED = "Der Spieler %1$s wurde von %2$s aus der Stadt gewurfen.";
    public static String COMMAND_TOWN_DISBAND_LASTTOWN = "Du kannst die letzte Stadt deiner Fraktion nicht auflösen! Probier /faction disband.";
    public static String COMMAND_TOWN_LEAVE_LASTMAYOR = "Du kannst als letzter Bürgermeister deine Stadt nicht verlassen.";
    public static String COMMAND_TOWN_LEAVE_SUCCESS = "Du hast deine Stadt erfolgreich verlassen.";
    public static String COMMAND_TOWN_LEAVE_LEFT = "Der Spieler %1$s hat die Stadt verlassen.";
    public static String COMMAND_TOWN_LIST_HEADER = "§3 ==== Städte ====";
    public static String COMMAND_TOWN_LOGIN_SUCCESS = "Loginnachricht erfolgreich gesetzt.";
    public static String COMMAND_TOWN_NEW_DISTANCE = "Du bist zu nah an einem anderen Spieler/einer anderen Stadt.";
    public static String COMMAND_TOWN_NEW_EXISTS = "Es existiert bereits eine Stadt mit diesem Namen.";
    public static String COMMAND_TOWN_NEW_SUCCESS = "Stadtgründung erfolgreich.";
    public static String COMMAND_TOWN_NEW_BROADCAST = "Die Stadt %1$s wurde im Namen der Fraktion %2$s gegründet.";
    public static String COMMAND_TOWN_WELCOME_SUCCESS = "Willkommensnachricht erfolgreich gesetzt.";
    public static String COMMAND_TOWN_RENAME_SUCCESS = "Stadt erfolgreich umbenannt!";
    public static String COMMAND_TOWN_RENAME_BROADCAST = "Die Stadt %1$s wurde in %2$s umbenannt!";
    public static String COMMAND_TOWN_RENAME_EXISTS = "Es existiert bereits eine Stadt mit diesem Namen.";
    public static String COMMAND_TOWN_PLOT_NOT_OWN = "Dieser Plot gehört nicht deiner Stadt.";
    public static String COMMAND_TOWN_PLOT_ADD_SUCCESS = "Spieler/Gruppen erfolgreich zum Plot hinzugefügt.";
    public static String COMMAND_TOWN_PLOT_ASSIGN_SUCCESS = "Plot erfolgreich zugewiesen.";
    public static String COMMAND_TOWN_PLOT_ASSIGN_ASSIGNED = "Dir wurde der Plot %1$s zugewiesen.";
    public static String COMMAND_TOWN_PLOT_ASSIGN_NOTINTOWN = "Dieser Spieler ist nicht Mitglied deiner Stadt.";
    public static String COMMAND_TOWN_PLOT_CLAIM_OWNED = "Dieser Plot gehört schon jemanden.";
    public static String COMMAND_TOWN_PLOT_CLAIM_NOTNEXTTOWN = "Dieser Plot grenzt nicht an deine Stadt an.";
    public static String COMMAND_TOWN_PLOT_CLAIM_LIMIT = "Deine Stadt hat ihr Plotlimit erreicht.";
    public static String COMMAND_TOWN_PLOT_CLAIM_SUCCESS = "Plot erfolgreich geclaimed.";
    public static String COMMAND_TOWN_PLOT_FLAG_SUCCESS = "Plotflag erfolgreich gesetzt.";
    public static String COMMAND_TOWN_PLOT_REMOVE_SUCCESS = "Spieler/Gruppen erfolgreich von Plot entfernt.";
    public static String COMMAND_TOWN_PLOT_SALE_SUCCESS = "Plot erfolgreich zum Verkauf gestellt.";
    public static String COMMAND_TOWN_PLOT_UNCLAIM_SUCCESS = "Plot erfolgreich unclaimed.";
    public static String COMMAND_TOWN_PLOT_UNSALE_SUCCESS = "Plot erfolgreich vom Verkauf entfernt.";
    public static String QUESTION_FACTION_DISBAND_QUESTION = "Möchtest du wirklich die Fraktion auflösen? [yes|no]";
    public static String QUESTION_FACTION_DISBAND_SUCCESS = "Fraktion erfolgreich aufgelöst.";
    public static String QUESTION_FACTION_DISBAND_BROADCAST = "Die Fraktion %1$s hat sich aufgelöst.";
    public static String QUESTION_FACTION_DISBAND_CANCELLED = "Fraktionsauflösung abgebrochen.";
    public static String QUESTION_FACTION_GIFT_LEADER_CANCELLED = "Stadtschenkung abgebrochen.";
    public static String QUESTION_FACTION_GIFT_LEADER_NEXT = "Die Bürgermeister der Stadt wird nun gefragt.";
    public static String QUESTION_FACTION_GIFT_LEADER_QUESTION = "Möchtest du die Stadt %1$s wirklich an die Fraktion %2$s verschenken? [yes|no]";
    public static String QUESTION_FACTION_GIFT_MAYOR_QUESTION = "Möchtest du, dass deine Stadt an %2$s verschenkt wird? [yes|no]";
    public static String QUESTION_FACTION_GIFT_MAYOR_NEXT = "Die Leader der anderen Fraktion werden nun gefagt.";
    public static String QUESTION_FACTION_GIFT_MAYOR_CANCELLED = "Stadtschenkung abgebrochen.";
    public static String QUESTION_FACTION_GIFT_MAYOR_CANCELLED_LEADER = "Ein Bürgermeister der Stadt hat die Schenkung abgelehnt.";
    public static String QUESTION_FACTION_GIFT_OTHER_QUESTION = "Die Fraktion %1$s möchte euch die Stadt %2$s schenken. [yes|no]";
    public static String QUESTION_FACTION_GIFT_OTHER_CANCELLED = "Stadtschenkung abgebrochen.";
    public static String QUESTION_FACTION_GIFT_OTHER_CANCELLED_SUBS = "Die Fraktion %1$s hat das Angebot der Stadtschenkung abgelehnt.";
    public static String QUESTION_FACTION_GIFT_SUCCESS = "Die Stadt %1$s von Fraktion %2$s wurde an die Fraktion %3$s verschenkt.";
    public static String QUESTION_TOWN_DISBAND_SUCCESS = "Stadt erfolgreich aufgelöst.";
    public static String QUESTION_TOWN_DISBAND_BROADCAST = "Die Stadt %1$s wurde aufgelöscht.";
    public static String QUESTION_TOWN_DISBAND_CANCELLED = "Stadtauflösung abgebrochen.";
    public static String QUESTION_TOWN_DISBAND_QUESTION = "Möchtest du deine Stadt wirklich auflösen? [yes|no] (Du verlässt damit deine Fraktion!)";
    public static String QUESTION_TOWN_INVITE_JOINED = "%1$s ist der Stadt beigetreten.";
    public static String QUESTION_TOWN_INVITE_ACCEPTED = "Du hast die Stadteinladung angenommen.";
    public static String QUESTION_TOWN_INVITE_CANCELLED = "Du hast die Einladung abgelehnt.";
    public static String QUESTION_TOWN_INVITE_QUESTION = "Die Stadt %1$s hat dir eine Einladung geschickt. [yes|no]";
    public static String QUESTION_TOWN_INVITE_INTOWNP = "Du kannst diese Einladung nicht annehmen, da du bereits in einer Stadt bist.";
    public static String QUESTION_TOWN_INVITE_INTOWNT = "%1$s konnte die Einladung nicht annehmen, da er bereits in einer Stadt ist.";
    public static String BUILDING_INVENTORY_FULL = "Dein Inventar ist zu voll.";
    public static String ECONOMY_NOT_ENOUGH_MONEY = "Du hast nicht genug Geld.";
    
    @SuppressWarnings("unused")
    protected static void loadStrings(FileConfiguration config)
    {
        // COMMAND_PERMISSION = config.getString("string.COMMAND_PERMISSION");
    }
}
